spring.application.name=CourseManagementSystem

# DB Credentials (We'll hide these in a minute)
spring.datasource.url=jdbc:postgresql://database.cy908kmy8epd.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=contrasenas

# Other Settings
spring.jpa.hibernate.ddl-auto=update